export default {
  string: '@string',
  string_email: '@email',
  string_phone: '@phone',
  string_username: '@cname',
  string_url: '@url',
  string_id: '@guid',
  string_csentence: '@csentence',
  string_cname: '@cname',
  string_errorCode: '@increment',
  string_county: '@county(true)',
  'string_string(16)': 'string(16)',
  'string_date-time': '@datetime',
  string_date: '@date',
  number: '@integer(60, 100)',
  number_float: '@float(60, 100, 3, 5)',
  integer: '@integer(60, 100)',
  boolean: '@boolean',
};
